name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

env:
  DEPLOYMENTS: ./build/deployments.json
  BUILD: ./build
  INDEX: ./build/index.html

jobs:
  update_index_push_to_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check for './build'
      # Setup Python
      # Build './index.html'
      # Flatten directories
      # Cleanup 
      # Push to production

      - name: üßê Check for build, index.html and deployments.json
        run: |
          # ------------
          # Ensure files
          # ------------

          declare -a missing
          
          if ! [[ -d "$BUILD" ]]; then
            missing+=("build")
          fi

          if ! [[ -f "$DEPLOYMENTS" ]]; then
            missing+=("build/deployments.json")
          fi
          
          if ! [[ -f "$INDEX" ]]; then
            missing+=("build/index.html")
          fi
          
          if ! [[ ${#missing[*]} -eq 0 ]]
          then
            echo "::error ::Missing files from 'staging' branch."
            echo "Missing: ${missing[*]}"
            exit 1
          else
            exit 0
          fi

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: üñé Update index.html, parse opt-outs
        run: |
          pip install -r ./scripts/requirements.txt
          python ./scripts/update_root_index.py

      - name: Unpack subfolders to improve page navigation
        run: |
          rm $DEPLOYMENTS
          rm $INDEX
          git mv $BUILD/* .

      - name: üßπ Cleanup
        run: rmdir $BUILD
      
      - name: Create .nojekyll file to avoid problems with CSS
        run: touch .nojekyll

      - name: üö† Push to production
        uses: EndBug/add-and-commit@v9
        with:
          message: Deploying build
          add: '.'
          push: origin HEAD:production --force

