name: Staging

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

env:
  DEPLOYMENTS: ./build/deployments.json
  BUILD: ./build
  INDEX: ./index.html

jobs:
  update_index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check for './build'
      # Setup Python
      # Rebuild './index.html'
      # Save './build' and './index.html' as artifacts

      - name: Check for build, index.html and deployments.json
        run: |
          # ------------
          # Ensure files
          # ------------

          declare -a missing
          
          if ! [[ -d "$BUILD" ]]; then
            missing+=("build")
          fi

          if ! [[ -f "$DEPLOYMENTS" ]]; then
            missing+=("build/deployments.json")
          fi
          
          if ! [[ -f "$INDEX" ]]; then
            missing+=("index.html")
          fi
          
          if ! [[ ${#missing[*]} -eq 0 ]]
          then
            echo "::error ::Missing files from 'staging' branch."
            echo "Missing: ${missing[*]}"
            exit 1
          else
            exit 0
          fi

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Update index.html, parse opt-outs
        run: |
          pip install -r ./scripts/requirements.txt
          python ./scripts/update_root_index.py

      - name: Cleanup
        run: rm $DEPLOYMENTS
    
  deploy_to_production:
    runs-on: ubuntu-latest
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    needs: [update_index]
    steps:
      - uses: actions/checkout@v3

      - uses: EndBug/add-and-commit@v9
        with:
          message: Deploying build
          add: '["build", "index.html"]'
          push: origin HEAD:production --force
